alumnosBundle\Entity\Alumnos:
    type: entity
    table: alumnos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        test:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
